### ISSUE TITLE
Discord Tools v1.2

### ISSUE THREAD

**Issue by Makarov135711** [PapaSnags/Discord-Tools#1]
The main issue is we cant copy the Token into your software.Whenever i use to copy the code i can copy and paste it in the notepad but i can't paste it in your software(Discord tools),the paste and some other options appear to be faded.
![IMG_20201002_185424](https://user-images.githubusercontent.com/72262270/94928212-f84e5280-04e0-11eb-98ce-5674b2bfef74.jpg)

**Comment by PapaSnags** [comment]
You need to click "update" paste your token then "save"
